[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = {path = "../shared"}
bevy.workspace = true
netcode.workspace = true
serde.workspace = true
uuid.workspace = true
slotmap.workspace = true
endlessgrid.workspace = true