// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message = { "joinAsPlayer": { 
/**
 * player id, generated by player
 */
id: string, 
/**
 * self chosen name of the player
 */
name: string, } } | { "welcomePlayer": { your_entity: bigint, } } | { "tileUpdate": { 
/**
 * index of the tile
 */
index: [number, number], 
/**
 * if the tile is a wall
 */
wall: boolean | null, 
/**
 * if the tile is visible
 */
visible: boolean | null, } } | { "thingUpdate": { 
/**
 * id of the thing
 */
id: bigint, 
/**
 * position of the thing
 */
x: number | null, 
/**
 * position of the thing
 */
y: number | null, 
/**
 * classes of the thing
 */
classes: string | null, 
/**
 * if the thing is visible or not
 */
visible: boolean | null, } };