use glam::IVec2;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Serialize, Deserialize)]
pub enum Message {
    JoinAsPlayer {
        /// player id, generated by player
        id:Uuid,
        /// self chosen name of the player
        name:String
    },
    WelcomePlayer {
        your_entity:u64
    },
    TileVisible {
        /// pos of the tile
        pos:IVec2,

        /// if the tile is a wall
        wall:bool
    }
}
//impl netcode::Msg for Message {};