use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Serialize, Deserialize)]
pub enum Message {
    JoinAsPlayer {
        /// player id, generated by player
        id:Uuid,
        /// self chosen name of the player
        name:String
    }
}
//impl netcode::Msg for Message {};